include $(GNUSTEP_MAKEFILES)/common.make 

TOOL_NAME=Hello 
Hello_OBJC_FILES=./src/main.m ./src/Tire.m ./src/Engine.m ./src/Car.m ./src/Slant6.m ./src/AllWeatherRadial.m

include $(GNUSTEP_MAKEFILES)/tool.make 
